export const GENRES = [
  "Romance",
  "Thriller",
  "Drama",
  "Comedy",
  "Action",
  "Fantasy",
  "Sci-Fi",
  "Horror",
  "Mystery",
  "Historical",
  "Slice of Life",
  "Revenge",
  "CEO/Billionaire",
  "Supernatural",
  "Crime",
];

export const PLATFORMS = [
  "ReelShort",
  "DramaBox",
  "ShortTV",
  "FlexTV",
  "GoodShort",
  "MoboReels",
  "HiTV",
  "TopShort",
  "YouTube Shorts",
  "TikTok",
  "Instagram Reels",
  "Other",
];

export const TROPE_TAGS = [
  "Secret Identity",
  "Rags to Riches",
  "Enemies to Lovers",
  "Love Triangle",
  "Revenge Arc",
  "Hidden Heir",
  "Contract Marriage",
  "Amnesia",
  "Time Skip",
  "Betrayal",
  "Power Struggle",
  "Mistaken Identity",
  "Forbidden Love",
  "Second Chance",
  "Underdog Rise",
  "Family Secrets",
  "Double Life",
  "Cliffhanger Reveal",
  "Fake Relationship",
  "Slow Burn",
  "Flashback",
  "Plot Twist",
  "Sacrifice",
  "Reunion",
  "Jealousy Arc",
];
