import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  header: { marginBottom: 20 },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#6b7280" },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingBottom: 4 },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#f3f4f6", paddingVertical: 4 },
  headerRow: { flexDirection: "row", borderBottomWidth: 2, borderBottomColor: "#d1d5db", paddingBottom: 4, marginBottom: 2, fontWeight: "bold" },
  cell: { flex: 2, paddingRight: 4 },
  cellSm: { flex: 1, textAlign: "right", paddingRight: 4 },
  summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  summaryCard: { width: "48%", padding: 12, backgroundColor: "#f9fafb", borderRadius: 4 },
  summaryLabel: { fontSize: 8, color: "#6b7280", textTransform: "uppercase" },
  summaryValue: { fontSize: 16, fontWeight: "bold", marginTop: 2 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9ca3af" },
});

export function PortfolioReportDocument({ workspaceName, seriesData, dateRange }) {
  const totals = seriesData.reduce(
    (acc, s) => ({
      views: acc.views + s.totalViews,
      revenue: acc.revenue + s.totalRevenue,
      episodes: acc.episodes + s.episodeCount,
    }),
    { views: 0, revenue: 0, episodes: 0 }
  );

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{workspaceName} — Monthly Portfolio Report</Text>
          <Text style={styles.subtitle}>
            {dateRange?.from || "All time"} to {dateRange?.to || "present"}
          </Text>
        </View>

        <View style={styles.summaryGrid}>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Total Series</Text>
            <Text style={styles.summaryValue}>{seriesData.length}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Total Episodes</Text>
            <Text style={styles.summaryValue}>{totals.episodes}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Total Views</Text>
            <Text style={styles.summaryValue}>{totals.views.toLocaleString()}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Total Revenue</Text>
            <Text style={styles.summaryValue}>${(totals.revenue / 100).toFixed(2)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Series Breakdown</Text>
          <View style={styles.headerRow}>
            <Text style={styles.cell}>Series</Text>
            <Text style={styles.cellSm}>Episodes</Text>
            <Text style={styles.cellSm}>Views</Text>
            <Text style={styles.cellSm}>Retention</Text>
            <Text style={styles.cellSm}>Revenue</Text>
          </View>
          {seriesData.map((s) => (
            <View key={s.id} style={styles.row}>
              <Text style={styles.cell}>{s.title}</Text>
              <Text style={styles.cellSm}>{s.episodeCount}</Text>
              <Text style={styles.cellSm}>{s.totalViews.toLocaleString()}</Text>
              <Text style={styles.cellSm}>{s.avgRetention.toFixed(1)}%</Text>
              <Text style={styles.cellSm}>${(s.totalRevenue / 100).toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>Generated by Reelytics — {new Date().toLocaleDateString()}</Text>
      </Page>
    </Document>
  );
}
