import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  header: { marginBottom: 20 },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#6b7280" },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 8, borderBottomWidth: 1, borderBottomColor: "#e5e7eb", paddingBottom: 4 },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#f3f4f6", paddingVertical: 4 },
  headerRow: { flexDirection: "row", borderBottomWidth: 2, borderBottomColor: "#d1d5db", paddingBottom: 4, marginBottom: 2, fontWeight: "bold" },
  cell: { flex: 1, paddingRight: 4 },
  cellRight: { flex: 1, textAlign: "right", paddingRight: 4 },
  summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  summaryCard: { width: "48%", padding: 12, backgroundColor: "#f9fafb", borderRadius: 4 },
  summaryLabel: { fontSize: 8, color: "#6b7280", textTransform: "uppercase" },
  summaryValue: { fontSize: 16, fontWeight: "bold", marginTop: 2 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#9ca3af" },
});

export function SeriesReportDocument({ series, episodes, metrics, dateRange }) {
  const totalViews = metrics.reduce((sum, m) => sum + (m.views || 0), 0);
  const totalRevenue = metrics.reduce((sum, m) => sum + (m.revenue_cents || 0), 0);
  const avgRetention = metrics.length
    ? metrics.reduce((sum, m) => sum + (m.avg_percent_watched || 0), 0) / metrics.length
    : 0;
  const totalUnlocks = metrics.reduce((sum, m) => sum + (m.unlocks || 0), 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{series.title} — Weekly Report</Text>
          <Text style={styles.subtitle}>
            {dateRange?.from || "All time"} to {dateRange?.to || "present"}
          </Text>
        </View>

        <View style={styles.summaryGrid}>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Total Views</Text>
            <Text style={styles.summaryValue}>{totalViews.toLocaleString()}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Avg Retention</Text>
            <Text style={styles.summaryValue}>{avgRetention.toFixed(1)}%</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Revenue</Text>
            <Text style={styles.summaryValue}>${(totalRevenue / 100).toFixed(2)}</Text>
          </View>
          <View style={styles.summaryCard}>
            <Text style={styles.summaryLabel}>Unlocks</Text>
            <Text style={styles.summaryValue}>{totalUnlocks.toLocaleString()}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Episode Performance</Text>
          <View style={styles.headerRow}>
            <Text style={styles.cell}>Episode</Text>
            <Text style={styles.cellRight}>Views</Text>
            <Text style={styles.cellRight}>Retention</Text>
            <Text style={styles.cellRight}>Revenue</Text>
          </View>
          {episodes.map((ep) => {
            const epMetrics = metrics.filter((m) => m.episode_id === ep.id);
            const views = epMetrics.reduce((s, m) => s + (m.views || 0), 0);
            const ret = epMetrics.length
              ? epMetrics.reduce((s, m) => s + (m.avg_percent_watched || 0), 0) / epMetrics.length
              : 0;
            const rev = epMetrics.reduce((s, m) => s + (m.revenue_cents || 0), 0);
            return (
              <View key={ep.id} style={styles.row}>
                <Text style={styles.cell}>
                  Ep {ep.episode_number}{ep.title ? ` — ${ep.title}` : ""}
                </Text>
                <Text style={styles.cellRight}>{views.toLocaleString()}</Text>
                <Text style={styles.cellRight}>{ret.toFixed(1)}%</Text>
                <Text style={styles.cellRight}>${(rev / 100).toFixed(2)}</Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.footer}>Generated by Reelytics — {new Date().toLocaleDateString()}</Text>
      </Page>
    </Document>
  );
}
